"""create geo table

Revision ID: 10d7a9e23349
Revises: 
Create Date: 2024-04-21 16:21:18.363031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d7a9e23349'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('geo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geo')
    # ### end Alembic commands ###
